"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Gamepad2, WalletCards, ChevronRight, Coins, Clock3, ShieldCheck, Sparkles, LoaderCircle, ListChecks } from "lucide-react";
import { supabase } from "../lib/supabase";

type PlayOffer = { id:string; title:string; description:string; category:string; icon:string; landingPage:string; tasks:{name:string;reward:number|null}[]; daysLeft:number|null };

export default function HomePage(){
  const [name,setName]=useState("Jugador"), [balance,setBalance]=useState("0.00"), [offers,setOffers]=useState<PlayOffer[]>([]), [loading,setLoading]=useState(true);
  useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.replace("/login");return;}const [{data:p},{data:w}]=await Promise.all([supabase.from("profiles").select("full_name,display_name").eq("id",session.user.id).maybeSingle(),supabase.from("wallets").select("coins").eq("user_id",session.user.id).maybeSingle()]);setName(p?.full_name?.trim().split(" ")[0]||p?.display_name||"Jugador");setBalance(((w?.coins??0)/1000).toFixed(2));try{const res=await fetch("/api/offers",{headers:{Authorization:"Bearer "+session.access_token}});const data=await res.json();setOffers(data.offers??[]);}catch{}setLoading(false);})()},[]);
  return <main className="app-shell home-simple">
    <header className="topbar"><Link className="brand" href="/"><img className="brand-logo" src="https://raw.githubusercontent.com/jacksonjacamo130-svg/PLAYNI/main/logo-playni.png" alt="PLAYNI"/></Link><Link className="balance account-balance" href="/wallet"><Coins size={16}/><strong>{"$"+balance}</strong><ChevronRight size={14}/></Link></header>
    <section className="home-welcome"><div><span className="eyebrow"><Sparkles size={13}/> PLAYNI</span><h1>Hola, {name} 👋</h1><p>Elige una oferta y empieza a ganar.</p></div><Link className="home-profile" href="/profile">Mi perfil</Link></section>
    <section className="earn-hero"><div><span className="eyebrow">TU SALDO</span><strong>{"$"+balance}</strong><span>Disponible en tu billetera</span></div><Link href="/games" className="primary-btn">GANAR AHORA <ChevronRight size={18}/></Link></section>
    <section className="simple-section"><div className="simple-head"><div><span className="eyebrow">RECOMENDADO</span><h2>Ofertas para ti</h2></div><Link href="/games">Ver todas <ChevronRight size={15}/></Link></div>{loading?<div className="simple-empty"><LoaderCircle className="spin" size={22}/><span>Cargando...</span></div>:offers.length?<div className="offer-row">{offers.slice(0,2).map(o=><article className="simple-offer" key={o.id}><div className="simple-offer-top">{o.icon?<img src={o.icon} alt=""/>:<span>🎮</span>}<div><span className="tag">{o.category}</span><h3>{o.title}</h3></div></div><div className="offer-meta"><span><Clock3 size={14}/> {o.daysLeft!=null?o.daysLeft+" días":"Tiempo disponible"}</span><b>{o.tasks.length||1} objetivos</b></div><a className="offer-link" href={o.landingPage} target="_blank" rel="noreferrer">VER OFERTA <ChevronRight size={15}/></a></article>)}</div>:<div className="simple-empty"><strong>Pronto verás tus ofertas aquí</strong><span>Las campañas aparecerán cuando haya ofertas disponibles para tu cuenta.</span></div>}</section>
    <section className="simple-section"><div className="simple-head"><div><span className="eyebrow">TU PROGRESO</span><h2>Mis tareas</h2></div><Link href="/tasks">Ver mis tareas <ChevronRight size={15}/></Link></div><div className="continue-card"><div className="continue-icon"><ListChecks size={23}/></div><div><strong>Continúa donde quedaste</strong><p>Las ofertas que empieces aparecerán aquí con tus objetivos y progreso.</p></div><ChevronRight size={20}/></div></section>
    <section className="how-simple"><span className="eyebrow">MUY FÁCIL</span><h2>¿Cómo ganas?</h2><div className="mini-steps"><div><b>1</b><span>Elige</span></div><div><b>2</b><span>Juega</span></div><div><b>3</b><span>Completa</span></div><div><b>4</b><span>Retira</span></div></div><p><ShieldCheck size={15}/> Cada objetivo validado suma a tu saldo.</p></section>
    <nav className="bottom-nav"><Link className="active" href="/">⌂<span>Inicio</span></Link><Link href="/games"><Gamepad2 size={20}/><span>Ganar</span></Link><Link href="/tasks"><ListChecks size={20}/><span>Mis tareas</span></Link><Link href="/wallet"><WalletCards size={20}/><span>Billetera</span></Link></nav>
  </main>;
}